### ISSUE TITLE
How to download MICCAI OpenSourcePapers? Please.

### ISSUE THREAD

**Issue by lizhogn** [JunMa11/MICCAI-OpenSourcePapers#8]
I want to download the MICCAI papers too. But I can't find the download website in MICCAI. Could you tell me what's the website? Beause I want to use python to download papers in the future. Thank you very much.

**Comment by JunMa11** [comment]
Sure, here you go:)
https://www.miccai2020.org/en/

![image](https://user-images.githubusercontent.com/19947331/97080381-63490000-162d-11eb-90ec-d8adeadd0bff.png)
